/**
 * Output Nodes - Send results via Gmail and save to Google Drive
 */

import nodemailer from 'nodemailer';
import { google } from 'googleapis';
import fs from 'fs';
import { WorkflowState } from '../types/index.js';

/**
 * Send analysis results via Gmail
 */
export async function sendEmail(
  state: WorkflowState,
  config: {
    user: string;
    password: string;
    recipients?: string[];
  }
): Promise<Partial<WorkflowState>> {
  console.log('📧 Sending analysis results via email...');

  if (!config.user || !config.password) {
    console.log('⚠️  Gmail credentials not configured, skipping email');
    return { emailSent: false };
  }

  try {
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: config.user,
        pass: config.password,
      },
    });

    const report = state.gptAnalysis;
    if (!report) {
      throw new Error('No analysis report available to send');
    }

    const htmlBody = `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
            h2 { color: #34495e; margin-top: 30px; }
            .summary { background: #ecf0f1; padding: 15px; border-radius: 5px; margin: 20px 0; }
            ul { padding-left: 20px; }
            li { margin: 10px 0; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 0.9em; }
            .stats { background: #3498db; color: white; padding: 15px; border-radius: 5px; margin: 20px 0; }
          </style>
        </head>
        <body>
          <h1>🚀 Amazon Listing Analysis Report</h1>

          <div class="stats">
            <strong>Analysis Date:</strong> ${new Date(report.generatedAt).toLocaleDateString()}<br>
            <strong>Listings Analyzed:</strong> ${state.scrapedListings.size}<br>
            <strong>Images Analyzed:</strong> ${Array.from(state.imageAnalysis.values()).reduce((sum, a) => sum + a.images.length, 0)}<br>
            <strong>Insights Generated:</strong> ${report.competitiveInsights.length + report.recommendations.length}
          </div>

          <h2>📊 Executive Summary</h2>
          <div class="summary">
            ${report.summary.split('\n').map(p => `<p>${p}</p>`).join('')}
          </div>

          <h2>🔍 Competitive Insights</h2>
          <ul>
            ${report.competitiveInsights.map(insight => `<li>${insight}</li>`).join('')}
          </ul>

          <h2>💡 Recommendations</h2>
          <ul>
            ${report.recommendations.map(rec => `<li>${rec}</li>`).join('')}
          </ul>

          <h2>🖼️ Image Quality Analysis</h2>
          <div class="summary">
            ${report.imageQualityAnalysis.split('\n').map(p => `<p>${p}</p>`).join('')}
          </div>

          ${state.errors.length > 0 ? `
          <h2>⚠️ Errors Encountered</h2>
          <ul>
            ${state.errors.map(e => `<li><strong>${e.step}</strong>: ${e.message}${e.asin ? ` (ASIN: ${e.asin})` : ''}</li>`).join('')}
          </ul>
          ` : ''}

          <div class="footer">
            <p>Generated by Listing Analysis Automation</p>
            <p>This is an automated report. For questions, please contact your team.</p>
          </div>
        </body>
      </html>
    `;

    const recipients = config.recipients || [config.user];

    await transporter.sendMail({
      from: config.user,
      to: recipients.join(', '),
      subject: `Amazon Listing Analysis - ${new Date().toLocaleDateString()}`,
      html: htmlBody,
    });

    console.log(`✅ Email sent successfully to ${recipients.join(', ')}`);

    return { emailSent: true };

  } catch (error) {
    console.error('❌ Failed to send email:', error);
    return {
      emailSent: false,
      errors: [
        ...state.errors,
        {
          step: 'email',
          message: error instanceof Error ? error.message : String(error)
        }
      ]
    };
  }
}

/**
 * Save analysis results to Google Drive
 */
export async function saveToGoogleDrive(
  state: WorkflowState,
  config: {
    credentialsPath: string;
    folderId?: string;
  }
): Promise<Partial<WorkflowState>> {
  console.log('💾 Saving analysis results to Google Drive...');

  if (!config.folderId) {
    console.log('⚠️  Google Drive folder ID not configured, skipping');
    return { driveSaved: false };
  }

  try {
    const credentials = JSON.parse(fs.readFileSync(config.credentialsPath, 'utf8'));

    const auth = new google.auth.GoogleAuth({
      credentials,
      scopes: ['https://www.googleapis.com/auth/drive.file'],
    });

    const drive = google.drive({ version: 'v3', auth });

    const report = state.gptAnalysis;
    if (!report) {
      throw new Error('No analysis report available to save');
    }

    // Create JSON file with full analysis data
    const analysisData = {
      generatedAt: report.generatedAt,
      summary: report.summary,
      competitiveInsights: report.competitiveInsights,
      recommendations: report.recommendations,
      imageQualityAnalysis: report.imageQualityAnalysis,
      listings: Array.from(state.scrapedListings.entries()).map(([asin, listing]) => ({
        asin,
        title: listing.title,
        price: listing.price,
        rating: listing.rating,
        reviewCount: listing.reviewCount,
        bullets: listing.bullets,
        imageCount: listing.images.length,
      })),
      imageAnalysis: Array.from(state.imageAnalysis.entries()).map(([asin, analysis]) => ({
        asin,
        imageCount: analysis.images.length,
      })),
      errors: state.errors,
    };

    const fileName = `listing-analysis-${new Date().toISOString().split('T')[0]}.json`;
    const fileContent = JSON.stringify(analysisData, null, 2);

    const response = await drive.files.create({
      requestBody: {
        name: fileName,
        mimeType: 'application/json',
        parents: [config.folderId],
      },
      media: {
        mimeType: 'application/json',
        body: fileContent,
      },
      fields: 'id,name,webViewLink',
    });

    console.log(`✅ Saved to Google Drive: ${response.data.name}`);
    console.log(`   Link: ${response.data.webViewLink}`);

    return { driveSaved: true };

  } catch (error) {
    console.error('❌ Failed to save to Google Drive:', error);
    return {
      driveSaved: false,
      errors: [
        ...state.errors,
        {
          step: 'googleDrive',
          message: error instanceof Error ? error.message : String(error)
        }
      ]
    };
  }
}
